[package]
name = "deb822-fast"
version = "0.1.0"
edition = "2021"
repository.workspace = true
homepage.workspace = true

[dependencies]
deb822-derive = { path = "../deb822-derive", version = "^0.2", optional = true }

[features]
derive = ["dep:deb822-derive"]
